################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_LIST := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications \
board \
build/applications \
build/board \
build/kernel/components/dfs/dfs_v1/filesystems/devfs \
build/kernel/components/dfs/dfs_v1/filesystems/elmfat \
build/kernel/components/dfs/dfs_v1/src \
build/kernel/components/drivers/core \
build/kernel/components/drivers/hwtimer \
build/kernel/components/drivers/ipc \
build/kernel/components/drivers/misc \
build/kernel/components/drivers/phy \
build/kernel/components/drivers/sdio \
build/kernel/components/drivers/serial \
build/kernel/components/finsh \
build/kernel/components/libc/compilers/common \
build/kernel/components/libc/compilers/newlib \
build/kernel/components/libc/posix/io/poll \
build/kernel/components/libc/posix/io/stdio \
build/kernel/components/net/lwip/lwip-2.1.2/src/api \
build/kernel/components/net/lwip/lwip-2.1.2/src/apps/ping \
build/kernel/components/net/lwip/lwip-2.1.2/src/core \
build/kernel/components/net/lwip/lwip-2.1.2/src/core/ipv4 \
build/kernel/components/net/lwip/lwip-2.1.2/src/netif \
build/kernel/components/net/lwip/port \
build/kernel/components/net/netdev/src \
build/kernel/components/net/sal/dfs_net \
build/kernel/components/net/sal/impl \
build/kernel/components/net/sal/socket \
build/kernel/components/net/sal/src \
build/kernel/components/utilities/ulog/backend \
build/kernel/components/utilities/ulog \
build/kernel/libcpu/risc-v/common \
build/kernel/src \
build/modules/enet \
build/modules/led \
build/modules/sdcard \
build/modules/usb_config \
build/packages/CherryUSB-v1.4.3/class/hub \
build/packages/CherryUSB-v1.4.3/class/wireless \
build/packages/CherryUSB-v1.4.3/core \
build/packages/CherryUSB-v1.4.3/osal \
build/packages/CherryUSB-v1.4.3/platform/rtthread \
build/packages/CherryUSB-v1.4.3/port/ehci \
build/packages/netutils-latest/iperf \
build/packages/netutils-latest/ntp \
build/packages/rt_vsnprintf_full-latest \
libraries/drivers \
libraries/hpm_sdk/arch/riscv/l1c \
libraries/hpm_sdk/components/debug_console \
libraries/hpm_sdk/components/dma_mgr \
libraries/hpm_sdk/components/enet_phy/rtl8201 \
libraries/hpm_sdk/drivers/src \
libraries/hpm_sdk/soc/HPM6300/HPM6360/boot \
libraries/hpm_sdk/soc/HPM6300/HPM6360 \
libraries/misc/rtt_interrupt_util \
libraries/misc/rtt_os_tick \
modules/enet \
modules/led \
modules/sdcard \
modules/usb_config \
packages/CherryUSB-v1.4.3/class/hub \
packages/CherryUSB-v1.4.3/class/wireless \
packages/CherryUSB-v1.4.3/core \
packages/CherryUSB-v1.4.3/osal \
packages/CherryUSB-v1.4.3/platform/rtthread \
packages/CherryUSB-v1.4.3/port/ehci \
packages/netutils-latest/iperf \
packages/netutils-latest/ntp \
packages/rt_vsnprintf_full-latest \
packages/wifi-host-driver-latest/porting/src/bsp \
packages/wifi-host-driver-latest/porting/src/hal \
packages/wifi-host-driver-latest/porting/src/resources \
packages/wifi-host-driver-latest/porting/src/rtos \
packages/wifi-host-driver-latest/porting/src/wlan \
packages/wifi-host-driver-latest/wifi-host-driver/WiFi_Host_Driver/resources/clm/COMPONENT_43438 \
packages/wifi-host-driver-latest/wifi-host-driver/WiFi_Host_Driver/resources/firmware/COMPONENT_43438 \
packages/wifi-host-driver-latest/wifi-host-driver/WiFi_Host_Driver/resources/resource_imp \
packages/wifi-host-driver-latest/wifi-host-driver/WiFi_Host_Driver/src/bus_protocols \
packages/wifi-host-driver-latest/wifi-host-driver/WiFi_Host_Driver/src \
rt-thread/components/dfs/dfs_v1/filesystems/devfs \
rt-thread/components/dfs/dfs_v1/filesystems/elmfat \
rt-thread/components/dfs/dfs_v1/src \
rt-thread/components/drivers/core \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/phy \
rt-thread/components/drivers/sdio \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/wlan \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/libc/posix/io/poll \
rt-thread/components/libc/posix/io/stdio \
rt-thread/components/net/lwip/lwip-2.1.2/src/api \
rt-thread/components/net/lwip/lwip-2.1.2/src/apps/ping \
rt-thread/components/net/lwip/lwip-2.1.2/src/core \
rt-thread/components/net/lwip/lwip-2.1.2/src/core/ipv4 \
rt-thread/components/net/lwip/lwip-2.1.2/src/netif \
rt-thread/components/net/lwip/port \
rt-thread/components/net/netdev/src \
rt-thread/components/net/sal/dfs_net \
rt-thread/components/net/sal/impl \
rt-thread/components/net/sal/socket \
rt-thread/components/net/sal/src \
rt-thread/components/utilities/ulog/backend \
rt-thread/components/utilities/ulog \
rt-thread/libcpu/risc-v/common \
rt-thread/src \
. \
startup/HPM6360 \
startup/HPM6360/toolchains/gcc \

